---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
    driver:
      box: ubuntu/precise64
      box_url: https://vagrantcloud.com/ubuntu/boxes/precise64/versions/12.04.4/providers/virtualbox.box
  - name: ubuntu-14.04
    driver:
      box: ubuntu/trusty64
      box_url: https://vagrantcloud.com/ubuntu/boxes/trusty64/versions/14.04/providers/virtualbox.box

suites:
  - name: default
    run_list:
      - recipe[inspeqtor::default]
    attributes: <%= IO.read("chef.json") %>
