---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
    driver:
      box: hashicorp/precise64
      box_url: https://vagrantcloud.com/hashicorp/precise64/version/2/provider/virtualbox.box
  - name: ubuntu-14.04
    driver:
      box: ubuntu/trusty64
      box_url: https://vagrantcloud.com/ubuntu/trusty64/version/1/provider/virtualbox.box

suites:
  - name: default
    run_list:
      - recipe[inspeqtor::default]
    attributes:
